/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class ClassDeclaration implements INode {

  public NodeToken f0;

  public Identifier f1;

  public NodeOptional f2;

  public NodeToken f3;

  public NodeListOptional f4;

  public NodeListOptional f5;

  public NodeToken f6;

  private static final long serialVersionUID = 144L;

  public ClassDeclaration(final NodeToken n0, final Identifier n1, final NodeOptional n2, final NodeToken n3, final NodeListOptional n4, final NodeListOptional n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public ClassDeclaration(final Identifier n0, final NodeOptional n1, final NodeListOptional n2, final NodeListOptional n3) {
    f0 = new NodeToken("class");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("{");
    f4 = n2;
    f5 = n3;
    f6 = new NodeToken("}");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
