/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Go n);

  public R visit(final MainClass n);

  public R visit(final ClassDeclaration n);

  public R visit(final VarDeclaration n);

  public R visit(final MethodDeclaration n);

  public R visit(final Type n);

  public R visit(final TypeLine n);

  public R visit(final Statement n);

  public R visit(final StatementLine n);

  public R visit(final Expression n);

  public R visit(final ExpressionLine n);

  public R visit(final ExpressionLineTwo n);

  public R visit(final AExpression n);

  public R visit(final NewLine n);

  public R visit(final Identifier n);

}
