/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final Go n);

  public void visit(final MainClass n);

  public void visit(final ClassDeclaration n);

  public void visit(final VarDeclaration n);

  public void visit(final MethodDeclaration n);

  public void visit(final Type n);

  public void visit(final TypeLine n);

  public void visit(final Statement n);

  public void visit(final StatementLine n);

  public void visit(final Expression n);

  public void visit(final ExpressionLine n);

  public void visit(final ExpressionLineTwo n);

  public void visit(final AExpression n);

  public void visit(final NewLine n);

  public void visit(final Identifier n);

}
