/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);


  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Go n, final A argu);

  public void visit(final MainClass n, final A argu);

  public void visit(final ClassDeclaration n, final A argu);

  public void visit(final VarDeclaration n, final A argu);

  public void visit(final MethodDeclaration n, final A argu);

  public void visit(final Type n, final A argu);

  public void visit(final TypeLine n, final A argu);

  public void visit(final Statement n, final A argu);

  public void visit(final StatementLine n, final A argu);

  public void visit(final Expression n, final A argu);

  public void visit(final ExpressionLine n, final A argu);

  public void visit(final ExpressionLineTwo n, final A argu);

  public void visit(final AExpression n, final A argu);

  public void visit(final NewLine n, final A argu);

  public void visit(final Identifier n, final A argu);

}
